name: Check for News

on:
  workflow_dispatch:
  pull_request_target:
    branches:
      - main

jobs:
  check-news-item:
    uses: scikit-package/release-scripts/.github/workflows/_check-news-item.yml@v0
    with:
      project: pdfbl.sequential
